### PR TITLE
Enable running FPGA tests in CI

### LINKED ISSUE #48: FPGA tests aren't fully running in CI
The production container test fails to run any of the FPGA tests because the tester container doesn't detect any FPGAs and then consequently disables those tests. This assumption works when the tester and server are running on the same container but not in the production test where the server is running in a separate container.

The tests should query the server to identify what hardware it has access to in order to enable the right sets of tests

### PR DESCRIPTION
**Pull request by varunsh-xilinx**
# Summary of Changes

*  Add `hasHardware` to the API

Closes #48

# Motivation

For CI and testing, we need to be able to check what devices the server has access to in order to run only the subset of tests that should succeed.

# Implementation

The `hasHardware` API allows a client to check whether the server has access to some number of a resource. Currently, only FPGA resources are checked but GPU and CPU resources can be checked in a similar way.

Enabling this check and running the test properly on the production container revealed some missing dependencies that this PR also addresses.

### CODE REVIEW

**Comment by balasaajay** [comment]
retest this please

**Comment by varunsh-xilinx** [comment]
retest this please

**Comment by varunsh-xilinx** [comment]
retest this please

**Comment by varunsh-xilinx** [comment]
retest this please

**Comment by varunsh-xilinx** [comment]
The PR tests are failing due to a timeout. I verified manually that it passes with an increased timeout value and I've made a PR to update the pipeline.

**Pull request merged**
